name: instant-ai-value
services:
  - name: backend
    github:
      repository: tombrewsviews/instant-ai-value
      branch: main
    instance_type: nano
    ports:
      - port: 8000
        protocol: http
    env:
      - key: NODE_ENV
        value: production
    build:
      builder: buildpack
    routes:
      - path: /
        port: 8000
    commands:
      - npm install
      - node server.js
    workdir: /workspace/src/backend
